var trainingdata = [
  {
    "title": "Data Science",
    "trainingtitle": "",
    "subtitle": "",
    "box1": "",
    "box2": "",
    "box3": "",
    "box4": "",
    "h1": "",
    "img": "assets/images/data.svg",
    "sh1": "",
    "p1": "",
    "sh2": "",
    "p2": "",
    "sh3": "",
    "p3": "",
    "url": "",
  },
  {
    "title": "Web Development",
    "trainingtitle": "Learn Web\nDevelopment",
    "subtitle":
        "Learn full-stack HTML/CSS, MySQL, PHP development and build an e-commerce website from scratch!",
    "box1": "4 Weeks",
    "box2": "Beginner Friendly",
    "box3": "3 Assignments, 1 project",
    "box4": "1:1 doubt solving",
    "h1": "Why Learn Web Development?",
    "img": "assets/images/webdevelopment.svg",
    "sh1": "Plenty of Jobs",
    "p1":
        "There will be approximately 1.4 million computing jobs available in 2020, with only 400,000 qualified developers to fill them, those interested in acquiring in-demand skills can certainly benefit from having web development and coding in their resume.",
    "sh2": "A Great Income",
    "p2":
        "A certified professional web developers earn an average salary of \$64,970 nation wide. Salary shouldn't be the only factor when deciding whether or not to learn web development, but it should be taken into consideration. ",
    "sh3": "Work From Anywhere",
    "p3":
        "Have freedom to work whenever you want from wherever—imagine that. All you need for web development is the internet and a laptop. Not all jobs are remote, but if that is your preference, there are remote jobs out there for you.",
    "url": "",
  },
  {
    "title": "Machine learning",
    "trainingtitle": "",
    "subtitle": "",
    "box1": "",
    "box2": "",
    "box3": "",
    "box4": "",
    "h1": "",
    "img": "assets/images/machinelearning.svg",
    "sh1": "",
    "p1": "",
    "sh2": "",
    "p2": "",
    "sh3": "",
    "p3": "",
    "url": "",
  },
  {
    "title": "Cloud",
    "trainingtitle": "",
    "subtitle": "",
    "box1": "",
    "box2": "",
    "box3": "",
    "box4": "",
    "h1": "",
    "img": "assets/images/Cloud.svg",
    "sh1": "",
    "p1": "",
    "sh2": "",
    "p2": "",
    "sh3": "",
    "p3": "",
    "url": "",
  },
  {
    "title": "Python",
    "trainingtitle": "",
    "subtitle": "",
    "box1": "",
    "box2": "",
    "box3": "",
    "box4": "",
    "h1": "",
    "img": "assets/images/python.svg",
    "sh1": "",
    "p1": "",
    "sh2": "",
    "p2": "",
    "sh3": "",
    "p3": "",
    "url": "",
  },
  {
    "title": "DevOps",
    "trainingtitle": "",
    "subtitle": "",
    "box1": "",
    "box2": "",
    "box3": "",
    "box4": "",
    "h1": "",
    "img": "assets/images/devops.svg",
    "sh1": "",
    "p1": "",
    "sh2": "",
    "p2": "",
    "sh3": "",
    "p3": "",
    "url": "",
  },
];
